services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipe-django-api
      - DB_USER=postgres
      - DB_PASS=postgres
      - DEBUG=true

      - RESEND_API_KEY=${RESEND_API_KEY:-changeme}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@example.com}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8000}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipe-django-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d recipe-django-api",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dev-db-data:
  dev-static-data:
