# Generated by Django 5.2.4 on 2025-07-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("user", "title")},
        ),
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="notes",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.CharField(
                help_text="e.g., '2 cups', '1 tbsp', '500g'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="core.recipe",
            ),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
